### ISSUE TITLE
Victor failed to connect

### ISSUE THREAD

**Issue by trentjw** [toreamun/victorsmartkill-homeassistant#31]
Logger: homeassistant.config_entries
Source: custom_components/victorsmartkill/__init__.py:63
Integration: Victor Smart-Kill ([documentation](https://github.com/toreamun/victorsmartkill-homeassistant), [issues](https://github.com/toreamun/victorsmartkill-homeassistant/issues))
First occurred: 12:57:27 AM (2 occurrences)
Last logged: 1:12:11 AM

Error setting up entry email for victorsmartkill
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/victorsmartkill/__init__.py", line 63, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, coordinator.platforms)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

**Comment by toreamun** [comment]
Duplicate of #29. Should work with HA 2022.8
