### ISSUE TITLE
Error setting up victorsmartkill

### ISSUE THREAD

**Issue by pertakman** [toreamun/victorsmartkill-homeassistant#30]
This integration stopped working for me.

The log message shows the following:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/victorsmartkill/__init__.py:63
Integration: Victor Smart-Kill (documentation, issues)
First occurred: 14:37:06 (1 occurrences)
Last logged: 14:37:06

Error setting up entry first.last@gmail.com for victorsmartkill
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/victorsmartkill/__init__.py", line 63, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, coordinator.platforms)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

I'm running version 2022.7.6 on a RPI4.

The version of the Victor component is 2022.7.1

Symptom: The integration does not appear to start properly.

**Comment by trentjw** [comment]
same issue

**Comment by toreamun** [comment]
Duplicate of #29. Should work with HA 2022.8
